### ISSUE TITLE
[Doc] document content typo?

### ISSUE THREAD

**Issue by tonyz0x0** [leptonai/leptonai#109]
The document for specifying resource type: https://www.lepton.ai/docs/walkthrough/resource_types, is using the flag `--resource-type`, yet in CLI [source code](https://github.com/leptonai/leptonai/blob/main/leptonai/cli/photon.py#L345) it is actually `--resource-shape`. I guess this is a typo on the documentation?

**Comment by Yangqing** [comment]
Thanks for catching this! Yes, definitely a typo. Fixing.
