### ISSUE TITLE
local api endpoints

### ISSUE THREAD

**Issue by freedomtrain** [leptonai/leptonai#110]
we are running locally on linux.
When we use curl we can send inputs": "Translate this text to French"
Are there other endpoints exposed ?

We tried this  "question": "Who is Frederick Douglass?"
and received "detail":"Not Found"}

Thanks !

**Comment by Yangqing** [comment]
If you are running locally on port 8080, the endpoints can be inspected at http://localhost:8080/docs as standard openapi - let me know whether it works!
