### ISSUE TITLE
[BUG]connection error

### ISSUE THREAD

**Issue by 13331112522** [leptonai/leptonai#123]
**Describe the bug**

Failed to create photon: 
(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max 
retries exceeded with url: /api/models/mistralai/Mistral-7B-Instruct-v0.1 
(Caused by SSLError(SSLCertVerificationError(1, "[SSL: 
CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, 
certificate is not valid for \'huggingface.co\'. (_ssl.c:997)")))'), '(Request 
ID: 92e7ab3a-6a8f-4b86-8626-9c40352a8499)')
**To Reproduce**

lep photon create --name mistral-7b --model hf:mistralai/Mistral-7B-Instruct-v0.1

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS
 - Python version: 3.10
 - LeptonAI library version: lep, version 0.11.0

**Additional context**
located in China and [redacted by repository admin to protect users' privacy] able to access huggingface.co.

**Comment by Yangqing** [comment]
Thanks for reporting the error!

Quick question - if you run the following python command:
```
import huggingface_hub
print(huggingface_hub.model_info("mistralai/Mistral-7B-Instruct-v0.1"))
```

Does the infor get print correctly? I suspect it might be a network connection issue that is unfortunately beyond our control...

**Comment by piamo** [comment]
> Thanks for reporting the error!
> 
> Quick question - if you run the following python command:
> 
> ```
> import huggingface_hub
> print(huggingface_hub.model_info("mistralai/Mistral-7B-Instruct-v0.1"))
> ```
> 
> Does the infor get print correctly? I suspect it might be a network connection issue that is unfortunately beyond our control...

My network can not access hf directly,  but I have got a hf model from somewhere. Can I use it like this:

```
lep photon run --name my_model --model hf:./my_local_model_dir
```

**Comment by 13331112522** [comment]
The bug has been fixed by changing the connection. But...

lep photon run --name mistral-7b --local

Launching photon on port: 8080
2023-10-24 19:24:21.694 | INFO     | leptonai.photon.hf.hf:pipeline:199 - Creating pipeline for text-generation(model=mistralai/Mistral-7B-Instruct-v0.1, revision=7ad57997).
HuggingFace download might take a while, please be patient...
2023-10-24 19:24:21.694 | INFO     | leptonai.photon.hf.hf:pipeline:204 - Note: HuggingFace caches the downloaded models in ~/.cache/huggingface/ (or C:\Users\<username>\.cache\huggingface\ on Windows). If you have already downloaded the model before, the download should be much faster. If you run out of disk space, you can delete the cache folder.
2023-10-24 19:24:22.579228: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Failed to launch photon: 'mistral'

**Comment by Yangqing** [comment]
This looks like a dependency issue and not one from lepton.

I'd suggest starting with a clean anaconda install, and use conda python to run `pip install lepton` - I think there is a conflict in the underlying C library between scipy and some other libraries, which is a common case if mac system python and other python installations are mixed up.

**Comment by bddppq** [comment]
Closing since the original issue has been addressed. Feel free to open new issues if you have run into other problems. Thanks
