### ISSUE TITLE
[BUG] issues with 'pad_token_id'

### ISSUE THREAD

**Issue by AnthonyZhai** [leptonai/leptonai#125]
**Describe the bug**
I've been learning leptonai with [offical tutorials](https://www.lepton.ai/docs/overview/quickstart#1-installation)

**To Reproduce**
Following the steps of offical tutorials, when i tend to post a request through either `curl` tools or a `python3` code (above). I will always got the error showed in the above picture.
```python3
from leptonai.client import Client, local
import os
#api_token = os.environ.get('LEPTON_API_TOKEN')
#client = Client('uzlymnrx', 'mygpt2', token=api_token)
client = Client(local(port=8080))
client.healthz()
client.paths()
print(client.run(inputs='Once upon a time'))
```
**Expected behavior**
Reciving the response of gpt2 model:
```
"Once upon a time, the warring powers of North Africa, Europe and Asia had their own different doctrines concerning its most sacred affairs, and for a while the idea of a common treaty was still in vogue. It has long been reported that after"
```

**Screenshots**
![WX20231023-184521@2x](https://github.com/leptonai/leptonai/assets/7577157/6a0c40a3-209b-4c01-b3a2-fb649a1ccb0e)

**Environment (please complete the following information):**
 - OS: [Mac OS Sonoma 14.0]
 - Python version: [3.10.0]
 - LeptonAI library version: [lep, version 0.11.0]

**Additional context**
I also tried deploied gpt2 model in the cloud, there is no error at all, everything works.
But i always got the error locally.

**Comment by Yangqing** [comment]
Bus error suggests that this is a python installation error and not from the lepton code - would you like to try a fresh python install?

I'd suggest starting with a clean anaconda install, and use conda python to run pip install lepton. Mixing system python and other libraries usually causes unexpected behaviors.

**Comment by bddppq** [comment]
The `pad_token_id` line is not an error. bus error seems more likely to be a hardware issue (or at least system level issue) rather than leptonai framework.
Feel free to re-open if you have new info available and we can further investigate.
