### ISSUE TITLE
[BUG] Public endpoint gives "upstream connect error"

### ISSUE THREAD

**Issue by slapcat** [leptonai/leptonai#254]
**Describe the bug**
Trying to run the test curl command at this page:

https://www.lepton.ai/playground/openvoice

And I get this error:

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

If I remove the env variable, it gives an "Unauthorized" message, so I don't think it is an authentication issue.

**To Reproduce**
```
export LEPTON_API_TOKEN="xxxxxxx"

curl 'https://openvoice.lepton.run/run' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer $LEPTON_API_TOKEN" \
  -d '{
     "reference_speaker": "https://www.lepton.ai/playground/openvoice/inputs/speaker_1.mp3",
     "text": "Hi, can you hear me?",
     "emotion": "friendly"
   }'\
  -o output.mp3

cat output.mp3
```

**Expected behavior**
The curl command generates a correct mp3 file with a recording of the text.

**Screenshots**
```
$ curl 'https://openvoice.lepton.run/run' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer $LEPTON_API_TOKEN" \
  -d '{
     "reference_speaker": "https://www.lepton.ai/playground/openvoice/inputs/speaker_1.mp3",
     "text": "Hi, can you hear me?",
     "emotion": "friendly"
   }'\
  -o output.mp3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   254  100    91  100   163     16     29  0:00:05  0:00:05 --:--:--    22
$ cat output.mp3 
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

**Environment (please complete the following information):**
 - OS: Linux Mint Debian Edition 6

**Comment by Yangqing** [comment]
Thanks for reporting this - it seems that I am able to do this, so it might be a transient connection issue? Would you mind retrying?
![Screenshot 2024-01-04 at 8 30 57 PM](https://github.com/leptonai/leptonai/assets/551151/4c5c1d1b-8432-42ea-a8b5-3d664eb71bfb)

**Comment by slapcat** [comment]
Yes, it works now. Thanks for the quick response!
