### ISSUE TITLE
How do I stop / pause a deployment instead of removing / deleting it?

### ISSUE THREAD

**Issue by HuaizhengZhang** [leptonai/leptonai#297]
**Is your feature request related to a problem? Please describe.**

As shown above, I can not find a button to pause my service.

![image](https://github.com/leptonai/leptonai/assets/5894780/0f3e600b-68c9-4a39-9b57-9fd4c4a4ef73)

I can not find the CLI for pausing/stopping a deployment, either.

Are there any other considerations for not having this functionality?

**Comment by Yangqing** [comment]
You can actually do "edit" and reduce the number of replicas to zero. Indeed we are planning to expose a "pause" button - cc @vthinkxie FYI.

**Comment by HuaizhengZhang** [comment]
Thanks for clarification.
