### ISSUE TITLE
Have you considered providing multiple sub classes in single python scripy?

### ISSUE THREAD

**Issue by JohnMasoner** [leptonai/leptonai#300]
**Is your feature request related to a problem? Please describe.**

I try to create multi photon, get
`bash
Failed to create photon: Found multiple sub classes of Photon in test.py: ['Counter', 'Counter1']
`
**Describe the solution you'd like**

Now:
```python
c = Client(local(8080))
print(f"Add 3, result: {c.add(x=3)}") # This will return 3
print(f"Add 5, result: {c.add(x=5)}") # This will return 8
print(f"Sub 2, result: {c.sub(x=2)}") # This will return 6
```

```bash
curl -X POST -H "Content-Type: application/json" -d '{"x": 3}' http://localhost:8080/add
```

Hope:
```python
c = Client(local(8080, 'Counter'))
print(f"C Add 3, result: {c.add(x=3)}") # This will return 3
print(f"C Add 5, result: {c.add(x=5)}") # This will return 8
print(f"C Sub 2, result: {c.sub(x=2)}") # This will return 6

c1 = Client(local(8080, 'Counter1'))
print(f"C1 Add 3, result: {c1.add(x=3)}") # This will return 3
print(f"C1 Add 5, result: {c1.add(x=5)}") # This will return 8
print(f"C1 Sub 2, result: {c1.sub(x=2)}") # This will return 6
```

```bash
curl -X POST -H "Content-Type: application/json" -d '{"x": 3}' http://localhost:8080/Counter/add
```

I'm not sure the need is justified in terms of security and privacy.

Mason

**Comment by Yangqing** [comment]
Yes, this is actually supported today - will put some code and example up.

**Comment by bddppq** [comment]
@JohnMasoner we should already support having multiple Photon subclasses in same python file. try adding `:{sub class name}` suffix to the command you used to create/launch photon. e.g. `lep photon create -n counter -m test.py:Counter1`
