### ISSUE TITLE
`lep login` on a headless machine?

### ISSUE THREAD

**Issue by felixding** [leptonai/leptonai#306]
**Is your feature request related to a problem? Please describe.**
I usually work on remote Linux box in the terminal. Is there any way to make `lep login` work?

**Describe the solution you'd like**
[Heroku](https://help.heroku.com/5I11S48T/i-need-to-log-in-to-the-cli-without-a-browser) solved this issue with a `-i` flag. However, if you are planning to support MFA, an alternative method would be preferable.

**Comment by bobmayuze** [comment]
You can login via token and workspace by copying the command from Settings page
<img width="1422" alt="image" src="https://github.com/leptonai/leptonai/assets/14257524/fdf98e86-c49a-48bd-8b33-549b0700c220">
