### ISSUE TITLE
‌‌[BUG] The Stable Diffusion Web UI page deployed online displays "Connection errored out."

### ISSUE THREAD

**Issue by devyujie** [leptonai/leptonai#309]
**Describe the bug**
The [Stable Diffusion Web UI](https://dashboard.lepton.ai/workspace/kmzou1o0/explore/detail/sd-webui-by-lepton) page deployed online displays "Connection errored out."

**To Reproduce**
/

**Expected behavior**
/

**Screenshots**
![image](https://github.com/leptonai/leptonai/assets/48620527/3b1b9e60-4bc1-482f-a598-2afed1bb24f0)

**Environment (please complete the following information):**
 - OS: Win10
 - Python version: 
 - LeptonAI library version: 

**Additional context**
/

**Comment by bddppq** [comment]
It was caused by our network gateway declined websockets connection. Fixed by updating gateway configuration. Please try again @devyujie
