### ISSUE TITLE
API Reference may be vague or unclear.[BUG]

### ISSUE THREAD

**Issue by iieoc** [leptonai/leptonai#312]
There are same API call example with two different API at lepton.ai,i am confused,may be It's not a bug!

**Comment by iieoc** [comment]
at this page :https://www.lepton.ai/references/image_processing#artistic-text-generation
![image](https://github.com/leptonai/leptonai/assets/38486399/fe7201fb-83c3-44c1-8a98-7689373013f7)
![image](https://github.com/leptonai/leptonai/assets/38486399/76e6e947-72bf-45b6-819e-991b930d4450)
QR Code and artistic text API and so on....they are same

**Comment by iieoc** [comment]
This API url:https://aiqr.lepton.run/generate,i think it is used to generate artistic text,i can't get any satisfied qrcode with this url.

**Comment by Yangqing** [comment]
Thanks for noticing this - cc'ing @bobmayuze to take a look :)

**Comment by bobmayuze** [comment]
Thanks for pointing it out, and they are the same code because the way to generate artistic QR codes or artistic texts is to provide a control image to start with. And a control images need to be passed in as base64 format.

**Comment by bddppq** [comment]
Yep same generation logic, just need to passing in different control images for different scenarios (art text vs. qrcode).
