### ISSUE TITLE
[BUG] Sorry, we might be overloaded, try again later.

### ISSUE THREAD

**Issue by Matr1xCode** [leptonai/leptonai#313]
Hello,

I don't know where I'm making a mistake, but once I launch the front end after following the documentation for the backend I hosted on your platform, I get this message after asking a question: 

Sorry, we might be overloaded, try again later.

Can anyone help me? Thank you

<img width="879" alt="Capture d’écran 2024-01-31 à 23 05 08" src="https://github.com/leptonai/leptonai/assets/119067298/1850cbf3-cdbf-4073-991b-0825a6aa6443">

**Comment by Yangqing** [comment]
It might be temporary - if you retry at another time, does things work? Also, kindly make sure you have done `lep login`.

**Comment by Rupert91** [comment]
I came across the same situation

**Comment by Rupert91** [comment]
I haven't resolved this issue either. I noticed the following error displayed in the developer console

<img width="365" alt="image" src="https://github.com/leptonai/leptonai/assets/153194923/46d0df7b-24d3-4da6-8ef4-05534fef5131">

**Comment by Yangqing** [comment]
We had an issue yesterday re supabase (supabase updated the service url and triggered some errors). It should be back now. For the error 403 forbidden - is that due to missing credentials? Make sure you do `lep login` to log in to your workspace.
