### ISSUE TITLE
[BUG] whisperx api will translate other language automatically.

### ISSUE THREAD

**Issue by suisuyy** [leptonai/leptonai#325]
**Describe the bug**
whisperx api will translate other language automatically. when send audio file by base64 string, 

**To Reproduce**
Steps to reproduce the behavior.
fetch(`https://whisperx.lepton.run/run`, {
            method: 'POST',
            headers: {
                Authorization: `Bearer token`,
                // Add other headers required by the API
                'Content-Type': 'application/json'

            },
            body: JSON.stringify({
                input: base64audiostring,
                language: model.language
            })
        });

**Expected behavior**
it should only transcribe, not translate to english
**Screenshots**

**Environment (please complete the following information):**
 - Python version: [e.g. 3.10]
 - LeptonAI library version: [obtain this via `lep --version`]

**Additional context**

**Comment by bobmayuze** [comment]
Did you pass in the language parameter? Based on the implementation and documentation [here](https://github.com/leptonai/leptonai/blob/9612d12d83a1ee708f9c07e4ec6cabcbe4d3bf8c/leptonai/templates/whisperx/whisperx.py#L208C1-L209C1), if it's not specified, the model will try to detect the language automatically

**Comment by suisuyy** [comment]
> Did you pass in the language parameter? Based on the implementation and documentation [here](https://github.com/leptonai/leptonai/blob/9612d12d83a1ee708f9c07e4ec6cabcbe4d3bf8c/leptonai/templates/whisperx/whisperx.py#L208C1-L209C1), if it's not specified, the model will try to detect the language automatically

thanks.
yeah, if i set language to zh(Chinese), sometimes it will translate to Chinese or not, if it's not specified, it  translate to English for most of time. i hope we can specify if it should translate like openai whisper: https://platform.openai.com/docs/api-reference/audio/createTranslation.

i have create a demo, can you try it:https://codepen.io/suisuyy/pen/jOJvpXL?editors=1010,
the default audio is japanese, but after clicking transcribe, you will get english 'good morning' as result

**Comment by bobmayuze** [comment]
As indicated in this [line](https://github.com/leptonai/leptonai/blob/9612d12d83a1ee708f9c07e4ec6cabcbe4d3bf8c/leptonai/templates/whisperx/whisperx.py#L197), if you can pass in a result with specified language, it should do it. Here is a screen shot on me passing in different langeuages.

<img width="1074" alt="image" src="https://github.com/leptonai/leptonai/assets/14257524/f74687e0-6ce7-4e41-9224-154f97cee127">

**Comment by Yangqing** [comment]
Thanks for the issue - this is indeed a bug in the default parameter. In the implementation:

https://github.com/leptonai/leptonai/blob/89f004e3b2af7b0e14221af26eeb82018e6b7c4d/leptonai/templates/whisperx/whisperx.py#L197

we have a default language set to "en" which stops one from language autodetection. If you know specifically the language of choice, like @bobmayuze mentioned, you can pass in for example `language="ja"` manually.

Re the bug - I'll change the code and update the deployment.

**Comment by Yangqing** [comment]
@suisuyy I am closing the issue for now - but feel free to reopen if there are still problems :)

**Comment by suisuyy** [comment]
thanks, it works normally now.
the api behavior is better too, now client need send data URL like 'data:audio/mpeg;base64,//uQxAAAC+WPDaGEfKpP....' instead pure base64 string
