### ISSUE TITLE
Playground is only for demostration purpose

### ISSUE THREAD

**Issue by IICommitII** [leptonai/leptonai#343]
Models that are for demonstration purposes only, can we still use them via API and generate outputs? How are they priced? Or one cannot use these models via API at all?

**Comment by vthinkxie** [comment]
FYI

<img width="866" alt="Screenshot 2024-03-06 at 13 51 15" src="https://github.com/leptonai/leptonai/assets/1506722/3ba38a27-f496-42c2-8efd-698f8c20d3c1">

https://www.lepton.ai/docs/public_models/model_apis

**Comment by bddppq** [comment]
I think all models on the playground should have corresponding api
