### ISSUE TITLE
ADD ISSUE DESCRIPTION HEREBY

### ISSUE THREAD

**Issue by Arturik2011** [leptonai/leptonai#345]
ADD ISSUE DESCRIPTION HERE

Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
User Agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Embedder: vscode.dev

Extension version: 0.40.0

_Originally posted by @Cheapetsgrow in https://github.com/microsoft/vscode-remote-repositories-github/issues/431_

**Comment by Cheapetsgrow** [comment]
?...

**Comment by bddppq** [comment]
What's the issue?
