### ISSUE TITLE
Reduce dependency when installing leptonai

### ISSUE THREAD

**Issue by butzhang** [leptonai/leptonai#346]
**Is your feature request related to a problem? Please describe.**
By installing leptonai via poetry, the image size increased 10x resulted in longer deployment time.

**Describe the solution you'd like**
can we somehow have a core version or lighter version of leptonai so I can choose the one with or without additional dependency like CUDA?

**Additional context**
<img width="1541" alt="image" src="https://github.com/leptonai/leptonai/assets/4190704/92fbb76f-257b-4e5b-bdb7-a984ed87dfec">

I have attached the screenshot if image built with/without leptonai lib.

**Comment by bddppq** [comment]
this should have been fixed in the latest 0.18.0 release (split into two packages `leptonai` which doesn't have cuda dependencies and `leptonai[runtime]` which has full dependencies)

**Comment by butzhang** [comment]
> this should have been fixed in the latest 0.18.0 release (split into two packages `leptonai` which doesn't have cuda dependencies and `leptonai[runtime]` which has full dependencies)

Oh my! Thanks for doing it! I will test it later today and close once I confirmed it reduce the image size.

**Comment by butzhang** [comment]
<img width="1102" alt="image" src="https://github.com/leptonai/leptonai/assets/4190704/2b06ca51-32be-4dcc-b732-92a8d5cb74fa">

thanks it works!
