### ISSUE TITLE
[BUG] KV isn't working, even though the LEPTON_API_TOKEN environment variable is set.

### ISSUE THREAD

**Issue by jianzs** [leptonai/leptonai#354]
**Describe the bug**

I'm using KV in Photon, and I've set the LEPTON_API_TOKEN environment variable when creating the Deployment, but it still doesn't work properly.

```
RuntimeError: It seems that you are not logged in to any workspace yet. Please log in and then retry. To log in, use `lep login` from the commandline.
```

**To Reproduce**

Creating a KV in Photon results in an error.
```
KV(namespace, create_if_not_exists=True, wait_for_creation=True)
```

**Expected behavior**

Reading and writing KV normally.

**Environment (please complete the following information):**
 lep, version 0.18.1

**Comment by bddppq** [comment]
you need to set `LEPTON_WORKSPACE_TOKEN` environment variable and explicitly call `leptonai.api.workspace.login` in your code (or in the `lep login` command line)
