### ISSUE TITLE
 Typo in   https://www.lepton.ai/docs/build_you_own_model/anatomy_of_a_photon#adding-extra-files

### ISSUE THREAD

**Issue by liuhuan5415** [leptonai/leptonai#370]
Hello  team,

I hope you're doing well. I've found a small spelling mistake and thought it would be helpful to bring it to your attention for correction.
Details:
Location: https://www.lepton.ai/docs/build_you_own_model/anatomy_of_a_photon#adding-extra-files 
Incorrect Spelling:  pricate
Correct Spelling:  private

Thank you for your hard work on this project. I appreciate the opportunity to contribute, even in a small way.
Best regards,
lh

**Comment by bddppq** [comment]
Thanks for reporting! This has been fixed now
