### ISSUE TITLE
Typo in https://www.lepton.ai/docs/build_you_own_model/clients

### ISSUE THREAD

**Issue by liuhuan5415** [leptonai/leptonai#375]
Hello team,

I hope you're doing well. I've found a small spelling mistake and thought it would be helpful to bring it to your attention for correction.
Details:
Location: https://www.lepton.ai/docs/build_you_own_model/clients
Incorrect Spelling: specifid
Correct Spelling: specified

Thank you for your hard work on this project. I appreciate the opportunity to contribute, even in a small way.
Best regards,
lh

**Comment by bddppq** [comment]
Thanks for reporting. Typo has been fixed now.
