### ISSUE TITLE
[BUG] cannot find workspace

### ISSUE THREAD

**Issue by iali-rbt** [leptonai/leptonai#402]
**Describe the bug**

lep login
lep workspace login 

fails with following error 
RuntimeError: Cannot find the workspace with id /api/v1.

**To Reproduce**
lep login fnog4fwd:[redacted]
lep workspace login -i fnog4fwd -t [redacted]

**Expected behavior**
command execute successfully

**Environment (please complete the following information):**
 - OS: MacOs 14.4 (23E214)
 - Python version: 3.9.6
 - LeptonAI library version: lep, version 0.20.4

**Additional context**

**Comment by Yangqing** [comment]
Thanks for reporting the bug - identified that we had a temporary issue in workspace name resolver. Filed an internal issue https://github.com/leptonai/lepton/issues/8604 and assigning to @vthinkxie . Will circle back.

**Comment by iali-rbt** [comment]
Hi Yangqing,

sounds good!

Thanks

**Comment by Yangqing** [comment]
We are going to push a change to the CLI - and when #419 lands and a new version released, this should have a proper warning message on CLI as well.
