### ISSUE TITLE
[BUG]Wish OpenVoice API continue work

### ISSUE THREAD

**Issue by JavaProgrammerLB** [leptonai/leptonai#460]
**Describe the bug**
Looking for help, I built a [website](https://voice.yitianyigexiangfa.com/) that depends on [OpenVoice API ](https://www.lepton.ai/playground/openvoice)which reports "Failed to fetch" since 1st of August.  Can you fix the "Failed to fetch" Error

**To Reproduce**
1. Enter https://www.lepton.ai/playground/openvoice in Chrome
2. click ‘Generate’ button
3. i get the ’failed to fetch‘ error
<img width="1234" alt="截屏2024-08-04 16 43 43" src="https://github.com/user-attachments/assets/dc4bef25-74ce-46d9-b232-0975befddc32">

**Expected behavior**
expect to get generated voice file

**Screenshots**
<img width="1234" alt="截屏2024-08-04 16 43 43" src="https://github.com/user-attachments/assets/dc4bef25-74ce-46d9-b232-0975befddc32">

**Comment by bddppq** [comment]
Unfortunately OpenVoice devs decide to not continue this serverless API. You can refer to [openvoice repo](https://github.com/myshell-ai/OpenVoice) to run a dedicated deployment on our platform.

**Comment by JavaProgrammerLB** [comment]
Thank you for your reply and suggestions, but I don't quite agree with the statement that the services appearing under the playground section of Lepton AI are decided by the OpenVoice team on whether to deploy.
