### ISSUE TITLE
[HF task support] Unexpected output with a Meta-Llama-3.1-8B-Instruct based model

### ISSUE THREAD

**Issue by liouxy** [leptonai/leptonai#465]
**What huggingface task type would you like to support?**
text-genaration

**Specifically, what model are you interested in under this task type?**
[NeverSleep/Lumimaid-v0.2-8B](https://huggingface.co/NeverSleep/Lumimaid-v0.2-8B?not-for-all-audiences=true)

**Would you mind sharing a bit more, like use cases and errors you encountered?**
I deployed the model using the Lepton LLM engine. The only information provided on [this page](https://dashboard.lepton.ai/workspace/ewd2y2yg/compute/deployments/explore/detail/llm-by-lepton) was MODEL_PATH, and the deployment succeeded.
I can create a chat completion request using the OpenAI SDK. However, the results I receive are unexpected. The snapshot below is what I obtained from the webpage, and I received a similar result using the OpenAI SDK.
<img width="1868" alt="Snipaste_2024-08-09_13-39-50" src="https://github.com/user-attachments/assets/ea6f3cee-9368-4e91-a823-bc249dc62156">

I also attempted deployment on my own server using transformers, and the results appeared satisfactory.
<img width="1907" alt="Snipaste_2024-08-09_13-22-36" src="https://github.com/user-attachments/assets/7cd19a1a-acd5-4bc6-81dc-51994b1af7ec">

As shown in the [config.json](https://huggingface.co/NeverSleep/Lumimaid-v0.2-8B/blob/main/config.json), it is identical to the Llama-3.1-8B-Instruct's configuration. However, the results suggest there may be a tokenization error.

Please assist me in ensuring the deployment functions correctly in chat mode, thank you!

**Comment by bddppq** [comment]
Hi @liouxy we have released a new version of Lepton LLM Engine today (7v4vniao / Sep 3, 2024) that can automatically recognize the chat_template specified in the tokenizer_config.json file. It should work for your model NeverSleep/Lumimaid-v0.2-8B. Please give it a try.

**Comment by bddppq** [comment]
<img width="1667" alt="Screenshot 2024-09-03 at 6 02 57 PM" src="https://github.com/user-attachments/assets/29a60b96-336a-4e24-bc82-3030ffed22a9">

**Comment by Yangqing** [comment]
We'll update the documentation in https://github.com/leptonai/leptonai/pull/482 - feel free to give it a shot if there are non-standard templates in certain other models.
